variable "nic1" {}
variable "resourcegroup1" {}
variable "subnetoutput1" {}
variable "pip1" {}
variable "vm1" {}
variable "nic2" {}
variable "resourcegroup2" {}
variable "subnetoutput2" {}
variable "pip2" {}
variable "vm2" {}
variable "pip3" {}
variable "pip4" {}
